/**
 * fetch-fonts.mjs — one-time build step.
 * Self-hosts the three brand typefaces so the site has no external font
 * dependency at runtime. Downloads only the unicode subsets we actually use.
 * Run: node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(ROOT, 'public/fonts');
fs.mkdirSync(FONT_DIR, { recursive: true });

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { css: 'Fraunces:ital,opsz,wght@0,9..144,300..800;1,9..144,300..700', file: 'fraunces', subsets: ['latin', 'latin-ext'] },
  { css: 'Inter:wght@300..800', file: 'inter', subsets: ['latin', 'latin-ext'] },
  { css: 'Noto+Sans+Bengali:wght@400..700', file: 'noto-bengali', subsets: ['bengali'] },
];

const out = [];

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Split into blocks; each is preceded by a /* subset */ comment
  const blocks = css.split('/*').slice(1);
  let i = 0;
  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim();
    if (!fam.subsets.includes(subset)) continue;
    const body = raw.slice(raw.indexOf('*/') + 2);
    const srcMatch = body.match(/url\((https:[^)]+\.woff2)\)/);
    const styleMatch = body.match(/font-style:\s*([^;]+);/);
    const weightMatch = body.match(/font-weight:\s*([^;]+);/);
    const rangeMatch = body.match(/unicode-range:\s*([^;]+);/);
    if (!srcMatch) continue;

    const style = styleMatch ? styleMatch[1].trim() : 'normal';
    const name = `${fam.file}-${subset}-${style}-${i++}.woff2`;
    const bin = Buffer.from(await (await fetch(srcMatch[1], { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(FONT_DIR, name), bin);

    const family = fam.css.split(':')[0].replace(/\+/g, ' ');
    out.push(
      `@font-face{font-family:'${family}';font-style:${style};font-weight:${weightMatch[1].trim()};font-display:swap;src:url('/fonts/${name}') format('woff2');unicode-range:${rangeMatch[1].trim()}}`
    );
    console.log(`  ${name}  ${(bin.length / 1024).toFixed(1)} KB`);
  }
}

fs.mkdirSync(path.join(ROOT, 'src/styles'), { recursive: true });
fs.writeFileSync(
  path.join(ROOT, 'src/styles/fonts.css'),
  '/* Generated by scripts/fetch-fonts.mjs — self-hosted brand typefaces. Do not edit by hand. */\n' +
    out.join('\n') + '\n'
);
console.log(`\n${out.length} @font-face rules -> src/styles/fonts.css`);
